---
- name: Update repo cache and install a cron package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - cron
  notify:
    - Enable cron service
    - Restart cron service
